-- MySQL Script generated by MySQL Workbench
-- Thu Sep  7 16:44:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `osbb` DEFAULT CHARACTER SET utf8 ;
USE `osbb` ;

-- -----------------------------------------------------
-- Table `buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(5) NOT NULL,
  `square` FLOAT NOT NULL,
  `level` TINYINT(1) NOT NULL,
  `building_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_buildig_idx` (`building_id` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  CONSTRAINT `fk_flat2buildig`
    FOREIGN KEY (`building_id`)
    REFERENCES `buildings` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `members_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `members_role` (
  `member_id` INT NOT NULL,
  `role` ENUM('member', 'staff', 'manager', 'resident') NOT NULL DEFAULT 'member',
  INDEX `fk_role2member_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_role2member`
    FOREIGN KEY (`member_id`)
    REFERENCES `members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tanents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(120) NOT NULL,
  `auto_allow` TINYINT NULL DEFAULT 0,
  `member_id` INT NULL,
  `flat_id` INT NOT NULL,
  `tanentscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tanent2member_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_tanent2flat_idx` (`flat_id` ASC) VISIBLE,
  CONSTRAINT `fk_tanent2member`
    FOREIGN KEY (`member_id`)
    REFERENCES `members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tanent2flat`
    FOREIGN KEY (`flat_id`)
    REFERENCES `flats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `properties` (
  `member_id` INT NOT NULL,
  `flat_id` INT NOT NULL,
  INDEX `fk_property2member_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_property2flat_idx` (`flat_id` ASC) VISIBLE,
  CONSTRAINT `fk_property2member`
    FOREIGN KEY (`member_id`)
    REFERENCES `members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property2flat`
    FOREIGN KEY (`flat_id`)
    REFERENCES `flats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
